const DRAW_BODY = {
  BODY_COLOR: '#FEBA39',
  BODY_SHADOW_COLOR: '#FEBA39',
  BODY_SHADOW_BLUR: 25,
  BODY_TRANSPARENCY: 1,
  BODY_RADIO: 0.5,
  BODY_INITIAL_ELEMENTS: 3,
  BODY_PATH_ELEMENTS: 12,
}

export { DRAW_BODY }
