const DOUBLE_RECTANGLE = {
  DR_OUTSIDE_COLOR: 'green',
  DR_INSIDE_COLOR: 'RED',
  DR_LINE_WIDTH: 0.2,
  DR_OUTSIDE_SIDE: 2,
  DR_INSIDE_SIDE: 1,
  DR_TRANSPARENCY: 0.3,
}

export { DOUBLE_RECTANGLE }
