export const SNAKE_BASE_PROPERTIES = {
  SNAKE_POSITION: { x: 50, y: 150 },
  SNAKE_HEAD_RADIO: 11,
  SNAKE_INITIAL_ROTATION: 0,
  SNAKE_VELOCITY: 0.0,
  SNAKE_IS_TRASLATE: true,
} as const;

export const SNAKE_HEAD_PROPERTIES = {
  SNAKE_HEAD_COLR: "yellow",
  SNAKE_HEAD_TRANSPARENCY: 1,
  SNAKE_HEAD_SHADOW_COLOR: "blue",

  SNAKE_EYE_ONE_SCLERA_COLOR: "white",
  SNAKE_EYE_ONE_IRIS_COLOR: "black",
  SNAKE_EYE_ONE_PUPIL_COLOR: "white",

  SNAKE_EYE_ONE_SCLERA_SHADOW_COLOR: "transparent",
  SNAKE_EYE_ONE_IRIS_SHADOW_COLOR: "transparent",
  SNAKE_EYE_ONE_PUPIL_SHADOW_COLOR: "transparent",

  SNAKE_EYE_ONE_SCLERA_TRANSPARENCY: 1,
  SNAKE_EYE_ONE_IRIS_TRANSPARENCY: 1,
  SNAKE_EYE_ONE_PUPIL_TRANSPARENCY: 1,

  SNAKE_EYE_TWO_SCLERA_COLOR: "white",
  SNAKE_EYE_TWO_IRIS_COLOR: "black",
  SNAKE_EYE_TWO_PUPIL_COLOR: "white",

  SNAKE_EYE_TWO_SCLERA_SHADOW_COLOR: "transparent",
  SNAKE_EYE_TWO_IRIS_SHADOW_COLOR: "transparent",
  SNAKE_EYE_TWO_PUPIL_SHADOW_COLOR: "transparent",

  SNAKE_EYE_TWO_SCLERA_TRANSPARENCY: 1,
  SNAKE_EYE_TWO_IRIS_TRANSPARENCY: 1,
  SNAKE_EYE_TWO_PUPIL_TRANSPARENCY: 1,
} as const;
